[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {verion = "1.16.1", features = ["net", "io-util", "rt"]}
tracing = "0.1.29"
nom = "7.1.0"