[package]
name = "collections"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = {version = "0.12.0", features = ["ahash", "inline-more", "rayon", "ahash-compile-time-rng"]}
